
# Backend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        environment: galacticairlines  # Additional label to match Fargate profile
    spec:
      containers:
        - name: backend
          image: abhay93/galactic-airlines-backend:k4  # Backend repository
          ports:
            - containerPort: 5000
          env:
            - name: DATABASE_HOST
              value: "database-service"
            - name: DATABASE_USER
              value: "root"
            - name: DATABASE_PASSWORD
              value: "password"
            - name: DATABASE_NAME
              value: "galactic_airlines"
---
# Backend Service
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP  # Internal communication between frontend and backend
---
# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        environment: galacticairlines
    spec:
      containers:
        - name: frontend
          image: abhay93/fe:k5  # Frontend repository
          ports:
            - containerPort: 80
---
# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer  # Exposes frontend to the internet
